version: "3.4"

services:

  api:
    build:
      context: ./api
      target: development
    image: api-dev
    volumes:
      - ./api/:/code
      - ../data-modelling-storage-service/gen/python:/dmss
    environment:
      FLASK_DEBUG: 1
      ENVIRONMENT: local
      MONGO_AZURE_URI: ${MONGO_AZURE_URI}
      CHOKIDAR_USEPOLLING: "true"
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
      APPLICATION_HOME: /code/home
      FLASK_ENV: development
      DMSS_HOST: mainapi
      DMSS_PORT: 5000
    depends_on:
      - mainapi
    ports:
      - "5000:5000"



  db:
    image: mongo:3.4
    command: --quiet
    restart: unless-stopped
    logging:
      driver: "none"
    environment:
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf

  mainapi:
    image: mariner.azurecr.io/dmss
    restart: unless-stopped
    environment:
      ENVIRONMENT: local
      MONGO_INITDB_ROOT_USERNAME: maf
      MONGO_INITDB_ROOT_PASSWORD: maf
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: 1
      MONGO_AZURE_URI: ${MONGO_AZURE_URI}
      APPLICATION_HOME: /usr/src/app/api/home
    ports:
      - "8000:5000"
    depends_on:
      - db

