version: "3.4"

services:
  nginx:
    build: ./nginx/local

  api:
    build:
      target: development
    environment:
      FLASK_DEBUG: 1
      ENVIRONMENT: local
      MONGO_AZURE_URI: ${MONGO_AZURE_URI}
    ports:
      - "5000:5000"

  web:
    build:
      target: dev
    environment:
      - NODE_ENV=development
    ports:
      - "9229:9229"

  db:
    ports:
      - "27017:27017"
    logging:
      driver: "none"

  db-ui:
    depends_on:
      - db
    image: mongo-express:0.49
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: maf
      ME_CONFIG_MONGODB_ADMINPASSWORD: maf
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

