// tslint:disable
/**
 * Data Modelling Tool
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Something...
 * @export
 * @interface Blueprint
 */
export interface Blueprint {
  /**
   *
   * @type {string}
   * @memberof Blueprint
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof Blueprint
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof Blueprint
   */
  version?: string
}

export function BlueprintFromJSON(json: any): Blueprint {
  return {
    id: !exists(json, '_id') ? undefined : json['_id'],
    title: json['title'],
    version: !exists(json, 'version') ? undefined : json['version'],
  }
}

export function BlueprintToJSON(value?: Blueprint): any {
  if (value === undefined) {
    return undefined
  }
  return {
    _id: value.id,
    title: value.title,
    version: value.version,
  }
}
