// tslint:disable
/**
 * Data Modelling Tool
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 * Describes the result of uploading an image resource
 * @export
 * @interface ModelApiResponse
 */
export interface ModelApiResponse {
  /**
   *
   * @type {number}
   * @memberof ModelApiResponse
   */
  code?: number
  /**
   *
   * @type {string}
   * @memberof ModelApiResponse
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof ModelApiResponse
   */
  message?: string
}

export function ModelApiResponseFromJSON(json: any): ModelApiResponse {
  return {
    code: !exists(json, 'code') ? undefined : json['code'],
    type: !exists(json, 'type') ? undefined : json['type'],
    message: !exists(json, 'message') ? undefined : json['message'],
  }
}

export function ModelApiResponseToJSON(value?: ModelApiResponse): any {
  if (value === undefined) {
    return undefined
  }
  return {
    code: value.code,
    type: value.type,
    message: value.message,
  }
}
