---
- block:
  - ansible.builtin.debug:
      msg: "Installing TLS certificates"

  - name: Ensure 'tls_certificate_base_path' directory is present
    file:
      path: "{{ tls_certificate_base_path }}"
      state: directory
      recurse: yes
      owner: "{{ tls_file_permissions.owner }}"
      group: "{{ tls_file_permissions.group }}"
      mode: "{{ tls_file_modes.dir }}"

  - name: Ensure 'tls_certificate_pem' certificate file is present
    copy:
      dest: "{{ tls_certificate_pem_path }}"
      content: |
        {{ tls_certificate_pem }}
      force: yes
      owner: "{{ tls_file_permissions.owner }}"
      group: "{{ tls_file_permissions.group }}"
      mode: "{{ tls_file_modes.pem }}"

  - name: Ensure 'tls_certificate_authority_pem' CA certificate file is present
    copy:
      dest: "{{ tls_certificate_authority_pem_path }}"
      content: |
        {{ tls_certificate_authority_pem }}
      force: yes
      owner: "{{ tls_file_permissions.owner }}"
      group: "{{ tls_file_permissions.group }}"
      mode: "{{ tls_file_modes.cacrt }}"

  when:
    - configure_tls_certs
    - tls_certificate_pem is defined
    - tls_certificate_authority_pem is defined
  tags:
    - tls
    - ssl
    - services