/* tslint:disable */
/* eslint-disable */
/**
 * Data Modelling Tool
 * API for Data Modeling Tool (DMT)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enumeration.
 * @export
 * @enum {string}
 */
export enum JobStatus {
  Registered = 'registered',
  Starting = 'starting',
  Running = 'running',
  Failed = 'failed',
  Completed = 'completed',
  Removed = 'removed',
  Unknown = 'unknown',
}
