/* tslint:disable */
/* eslint-disable */
/**
 * Data Modelling Tool
 * API for Data Modeling Tool (DMT)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobStatus } from './job-status'

/**
 *
 * @export
 * @interface StatusJobResponse
 */
export interface StatusJobResponse {
  /**
   *
   * @type {JobStatus}
   * @memberof StatusJobResponse
   */
  status: JobStatus
  /**
   *
   * @type {string}
   * @memberof StatusJobResponse
   */
  log?: string
  /**
   *
   * @type {string}
   * @memberof StatusJobResponse
   */
  message: string
}
