// tslint:disable
/**
 * Data Modelling Tool
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import { Blueprint, BlueprintFromJSON, BlueprintToJSON } from '../models'

/**
 * no description
 */
export class BlueprintApi extends runtime.BaseAPI {
  /**
   * Returns all blueprints
   * Get all blueprints
   */
  async getBlueprintsRaw(): Promise<runtime.ApiResponse<Array<Blueprint>>> {
    const queryParameters: runtime.HTTPQuery = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request({
      path: `/index/blueprints`,
      method: 'GET',
      headers: headerParameters,
      query: queryParameters,
    })

    return new runtime.JSONApiResponse(response, jsonValue =>
      jsonValue.map(BlueprintFromJSON)
    )
  }

  /**
   * Returns all blueprints
   * Get all blueprints
   */
  async getBlueprints(): Promise<Array<Blueprint>> {
    const response = await this.getBlueprintsRaw()
    return await response.value()
  }
}
