export default [
  import('@dmt/blueprint'),
  import('@dmt/default-pdf'),
  import('@dmt/default-preview'),
  import('@dmt/yaml-view'),
  import('@dmt/dmt-app'),
  import('@dmt/analysis-platform'),
  import('@dmt/mermaid'),
  import('@dmt/sima-application-input'),
  import('@dmt/task'),
  import('@dmt/job-handlers'),
  import('@dmt/job'),
  import('@dmt/form'),
  import('@dmt/tabs'),
  import('@sintef/simpos-ui'),
  import('@sintef/simos-ui'),
  import('@sintef/marmo-ui'),
]
