export default [
  import('@dmt/default-form'),
  import('@dmt/default-pdf'),
  import('@dmt/default-preview'),
  import('@dmt/yaml-view'),
  import('@dmt/dmt-app'),
  import('@dmt/analysis-platform'),
  import('for-weather-plots'),
  import('@dmt/mermaid'),
  import('@dmt/task'),
  import('@dmt/job-handlers'),
  import('@dmt/job'),
  import('@dmt/form'),
  import('@dmt/tabs'),
]
