version: "3.8"

services:
  dmt-sre:
    build: .
    image: publicMSA.azurecr.io/dmt-job/srs:latest
    environment:
      SIMA_LICENSE: "NONE"
      PUBLIC_DMSS_API: http://dmss:5000
      DSIS_TOKEN: "none"
    networks:
      - data-modelling-storage-service_default
    volumes:
      - ./job_wrapper.py:/code/job_wrapper.py
      - ./init.sh:/code/init.sh
      - ./tmp:/var/opt/sima
    # The stask and compute-service-cfg are part of the DemoDS in DMT with static UUIDs
    command: >-
        /code/init.sh --input-id=AnalysisPlatformDS/9229e1f3-e94d-4cde-9fb6-a08031b0b04a

networks:
  data-modelling-storage-service_default:
    external: true