version: "3.8"

services:
  dmt-sre:
    build: .
    image: datamodelingtool.azurecr.io/dmt-job/srs:latest
    environment:
      PUBLIC_DMSS_API: http://dmss:5000
      DSIS_TOKEN: "none"
      SIMA_LICENSE: |
        NONE
    networks:
      - data-modelling-storage-service_default
    volumes:
      - ./job_wrapper.py:/code/job_wrapper.py
      - ./init.sh:/code/init.sh
      - ./tmp:/var/opt/sima
    # The stask and compute-service-cfg are part of the DemoDS in DMT with static UUIDs
    command: >-
      /code/init.sh --input-id=AnalysisPlatformDS/8329e1f3-e94d-4cde-9fb6-a08031b0b04a --reference-target=5583c9b0-d505-46c9-a157-94c79f4d7a6a.jobs.0.result

networks:
  data-modelling-storage-service_default:
    external: true
