version: "3.8"

services:
  dmt-sre:
    build: .
    image: publicMSA.azurecr.io/dmt-job/srs:latest
    environment:
      SIMA_LICENSE: "NONE"
      PUBLIC_DMSS_API: http://dmss:5000
    networks:
      - data-modelling-storage-service_default
    volumes:
      - ./job_wrapper.py:/code/job_wrapper.py
      - ./init.sh:/code/init.sh
      - ./tmp:/var/opt/sima
    # The stask and compute-service-cfg are part of the DemoDS in DMT with static UUIDs
    command: >-
        /code/init.sh --token=XXXXXX --application-input='"{\"type\":\"AnalysisPlatformDS/Blueprints/SIMAApplicationInput\",\"name\":\"exampleAppInput\",\"description\":\"example SIMA application input for local container\",\"inputType\":\"system/SIMOS/NamedEntity\",\"outputType\":\"system/SIMOS/NamedEntity\",\"input\":\"{\\\"type\\\":\\\"system/SIMOS/NamedEntity\\\",\\\"name\\\":\\\"exampleInputEntity\\\",\\\"description\\\":\\\"example\\\"}\",\"workflow\":\"someWorkflow\",\"workflowTask\":\"someWorkflowTask\",\"resultPath\":\"AnalysisPlatformDS/Data/Analysis/results\",\"resultReferenceLocation\":\"5483c9b0-d505-46c9-a157-94c79f4d7a6a.jobs.17.result\",\"SIMAComputeConfig\":{},\"stask\":{}}"'

networks:
  data-modelling-storage-service_default:
    external: true