version: "3.8"

services:
  dmt-srs:
    build: .
    image: publicMSA.azurecr.io/dmt-job/srs:latest
    environment:
#      SIMA_LICENSE: |
#        $(cat ./sima.lic)
      PUBLIC_DMSS_API: http://dmss:5000
    networks:
      - data-modelling-storage-service_default
    volumes:
      - ./job_wrapper.py:/code/job_wrapper.py
    # The stask and compute-service-cfg are part of the DemoDS in DMT with static UUIDs
    command: [
        "/code/init.sh",
        "--stask=DemoDS/8ec0d646-907c-4eba-9e65-24106236d61c",
        "--workflow=workflow",
        "--remote-run",
        "--compute-service-cfg=ForecastDS/15a4d888-3ab4-5bd2-9bd9-9614dcb066d5",
        "--input=waveDir=180",
        "--token=123",
        "--target=DemoDS/DMT-demo/SIMARuntimeService/results/"
    ]

networks:
  data-modelling-storage-service_default:
    external: true