version: "3.8"

services:
  dmt-srs:
    build:
      context: application
    image: mariner.azurecr.io/dmt-job/srs:latest
    environment:
      SIMA_LICENSE: ${SIMA_LICENSE}  # SIMA_LICENSE=$(cat ./sima.lic)
      DMSS_HOST: dmss
      DMSS_PORT: "5000"
    networks:
      - data-modelling-storage-service_default
    volumes:
      - ./application/dmt_job_wrapper.py:/code/dmt_job_wrapper.py
    ports:
#      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
    command: ["run", "--stask-id", "DemoDS/511e9fb0-c24e-4768-b4c4-1cb8f5f252f5"]

networks:
  data-modelling-storage-service_default:
    external: true