version: "3.8"

services:
  dmt-srs:
    build: .
    image: mariner.azurecr.io/dmt-job/srs:latest
    environment:
#      SIMA_LICENSE: |
#        $(cat ./sima.lic)
      DMSS_HOST: http://dmss:5000
    networks:
      - data-modelling-storage-service_default
    volumes:
      - ./dmt_job_wrapper.py:/code/dmt_job_wrapper.py
    # This stask is part of the DemoDS in DMT with a static UUID
    command: ["run", "--stask=DemoDS/8ec0d646-907c-4eba-9e65-24106236d61c", "--workflow=wave_180", "--token=123"]

networks:
  data-modelling-storage-service_default:
    external: true