name: build adocs

on:
  push:
    branches:
    - master
    - docs

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    name: Build and deploy docs to Github pages 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create docs build directory
      run: mkdir dist && chmod 777 dist      
    - name: Build docs
      id: adocbuild
      uses: equinor/asciidoctor-action@main
    - name: Deploy docs to githu pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist