on:
  workflow_dispatch:
  workflow_call:  # Workflow is meant to be called from another workflow, with the image tag as input
    inputs:
      image-tag:
        description: 'Which tag to set for the produced docker images'
        default: 'latest'
        required: true
        type: string
      oauth-redirect-url:
        description: 'redirect url for oauth. Should be the public url to access the web app'
        default: 'https://data-modelling-tool.app.radix.equinor.com'
        required: true
        type: string
    secrets:
      ACR_SECRET:
        required: false


env:
  IMAGE_REGISTRY: datamodelingtool.azurecr.io
  REGISTRY_USER: datamodelingtool
  API_IMAGE: datamodelingtool.azurecr.io/dm-job


jobs:
  build-and-publish-api-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Build and Publish API"
        run: |
          echo "Tagging with ${{ inputs.image-tag }}"
          docker login -u $REGISTRY_USER -p ${{ secrets.ACR_SECRET }} $IMAGE_REGISTRY
          docker pull $API_IMAGE
          echo $(git log -n 1 --format=format:'%h% %>(12) %cs %>(12,mtrunc)%aN%  %s %D') > ./api/src/version.txt
          docker build --cache-from $API_IMAGE --target prod --tag $API_IMAGE ./api
          docker tag $API_IMAGE $API_IMAGE:${{ inputs.image-tag }}
          docker push $API_IMAGE:${{ inputs.image-tag }}

