# For testing; configure and trigger analysis run from the CI
on:
  workflow_dispatch:  # Only manual trigger
    inputs:
      ANALYSIS_ID:
        description: 'Analysis to get config from, and append jobs to'
        required: true
        default: 'AnalysisPlatformDS/4483c9b0-d505-46c9-a157-94c79f4d7a6a'
      #TODO: Add name of stask/config as input

env:
  DMSS_API: https://dmss-data-modelling-tool-dev.radix.equinor.com/api/v1
  DMT_JOB_API: https://proxy-data-modelling-tool-dev.radix.equinor.com/api/job
  STASK_BLOB_PATH: "./mySTask.stask"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master

        - name: "Create some stask"
          run: echo "Some content" > "$STASK_BLOB_PATH"

        - name: "Download script"
          run: |
            curl "https://raw.githubusercontent.com/equinor/data-modelling-tool/master/scripts/upload-config-run-job.sh" \
            --output "./upload-config-run-job.sh"
            chmod +x ./upload-config-run-job.sh

        - name: "Run"
          run: |
            export DMSS_SECRET_TOKEN=${{ secrets.DMSS_TOKEN }}
            ./upload-config-run-job.sh "$INPUTS_ANALYSIS_ID" "$STASK_BLOB_PATH"
